#!/usr/bin/env python3
"""
Change gcode to Creality_Print filament selrcted
Author: Steve T
Version: 1.0
"""
import sys
import time
import traceback
filUsed = "; filament used [mm] = " #"0.00, 0.00, 33.91, 0.00"
filDefault = "; default_filament_colour = " # replace with ";;F5F8FE;"
filColour = "; filament_colour = " # get all at first "#585CF8;#8297EC;#F5F8FE;#40A934"
headerCP = "; generated by Creality_Print V"
headerOrca = "; generated by OrcaSlicer "
flushVolumes = "; flush_volumes_matrix = " #0,375,601,0
flushMult = "; flush_multiplier = " #1
headerNeeded = True
filDefaultNeeded = True
flushVolumesMaxNeeded = False # "6"
flushMultNeeded = False


print(str(len(sys.argv)) + " pyfileIN " + sys.argv[1])

def GetParams():
    params = {}
    for param in sys.argv[1:]:
        (paramName, paramValue) = param.split("=", 1) if "=" in param else (param, "true")
        params[paramName.lower()] = paramValue
    print("Params:\n%s\n"%(str(params)))
    return params
    

# changes comments to select from only enabled filaments
path = sys.argv[1]
params = GetParams()
pathout = path + (".txt" if params.get("test", "false") == "true" else "")
flushVolumesMaxNeeded = params.get("flushmax", False) # false or the max value from the command line
flushVolumes12MaxNeeded = params.get("flush12max", False)
if flushVolumes12MaxNeeded:
    flushVolumesMaxNeeded = flushVolumes12MaxNeeded

print("pyfileOUT " + pathout)

with open(path, 'r') as gcode:
    lines = gcode.readlines()

try:
    with open(pathout, 'w') as gcode:
        for line in lines:
            if line.startswith(filUsed):
                filUsedVal = line.replace(filUsed, "").split(", ")
                print("found filUsedVal\n%s"%line)
            if line.startswith(filColour):
                filColourVal = line.replace(filColour, "").split(";")
                print("found filColourVal\n%s"%line)

        filDefaultVal = []
        for inx in range(0, len(filColourVal)):
            filDefaultVal.append(filColourVal[inx] if float(filUsedVal[inx]) > 0.0 else "")
        filDefaultTxt = ";".join(filDefaultVal)
        for line in lines:
            if headerNeeded and line.startswith(headerOrca):
                line = line.replace(headerOrca, headerCP)
                headerNeeded = False
                print("replacing header - replacing with\n%s"%line)
            if filDefaultNeeded and line.startswith(filDefault):
                line = filDefault + filDefaultTxt + '\n'
                filDefaultNeeded = False
                print("replacing filDefaultTxt - replacing with\n%s"%line)
            if flushVolumesMaxNeeded and line.startswith(flushVolumes):
                lineOld = line
                flushVolumesVals = line.replace(flushVolumes, "").split(",")
                filaments = len(filColourVal)
                for (index, value) in enumerate(flushVolumesVals):
                    if flushVolumes12MaxNeeded and int(index) % filaments > 1:
                        continue
                    flushVolumesVals[index] = str(min(int(flushVolumesMaxNeeded), int(value))) if int(value) > 0 else value
                line = flushVolumes + ",".join(flushVolumesVals) + '\n'
                print("replacing flushVolumesVals (newMax = %s) - replacing '%s' with\n%s"%(flushVolumesMaxNeeded,lineOld.replace("\n", ""), line))
                flushVolumesMaxNeeded = False
            gcode.write(line)

except Exception as e:
    traceback.print_exc()
    input("Press Enter to continue...")


#time.sleep(10)